### ISSUE TITLE
OpenID

### ISSUE THREAD

**Issue by gokarter24** [Jessecar96/SteamAuth#3]
There is something wrong with the openID and the SteamAuth class, it won't allow me to login. Do I need anything special besides the callback functions/calls?

**Comment by Thymopat** [comment]
Maybe you can provide us with some more informations.

**Comment by Thymopat** [comment]
Hey gokarter24,

Last time I tried this repository too and I could not login in as you said.
I found out:
The SteamID was successfully saved in the $_Session variable. The problem was the IsUserLoggedIn() method was not returning true -> so you are logged out. To prevent this issue use
```php
if(isset($_SESSION['steamid']) && strpos($_SESSION['steamid'], "7656") === 0) {
	return true;
} else {
	return false;
}
```
(you can use here the Ternary Operators but I recommend in this situation the normal way of structuring the if statement) instead of 
```php
return isset($_SESSION['steamid']) ? strpos($_SESSION['steamid'], "7656") === 0: false;
```
The last line which you have to replace is not really helpfull because:
The if condition ```isset($_SESSION['steamid'])``` is valid than it will execute  ```strpos($_SESSION['steamid'], "7656") === 0``` but here is the error it´s not returning true the rest ```: false;``` is valid too. If you really want to use the short way to write it you can use this line 
```php
return isset($_SESSION['steamid']) && strpos($_SESSION['steamid'], "7656") === 0 ? true : false;
```

I hope I could help you out.

Kind regards,
Thymopat

**Comment by Darindaa** [comment]
Thanks

**Comment by Thymopat** [comment]
No Problem I´m happy that I helped out :)

**Comment by Darindaa** [comment]
Could you help me with a problem im facing aswell? if you have 2 mins maybe add me on steam so i can ask you a few questions? thanks.

**Comment by Thymopat** [comment]
Yeah sure. I´m new in github. We will see if I will find your profile.

**Comment by Darindaa** [comment]
Just gimme your profile and i'll add you. thanks.

**Comment by Thymopat** [comment]
Thymopat... there is only one profile out there with this name.

**Comment by Darindaa** [comment]
Added.
